service: document-qa

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: python3.11
  region: ${opt:region, 'us-west-2'}
  stage: ${opt:stage, 'development'}
  logRetentionInDays: 1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - bedrock:*
      Resource: "*"
plugins:
 - serverless-wsgi
 - serverless-python-requirements
custom:
 wsgi:
   app: app.app
   packRequirements: false
functions:
 app:
   handler: wsgi_handler.handler
   timeout: 30
   events:
     - http: ANY /
     - http: 'ANY {proxy+}'
